name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Build Electron app
        uses: netruk44/electron-forge-distributable-action@main
        with:
          target-maker: "@electron-forge/maker-zip"
          target-platform: ${{ matrix.os }}
          node-installer: "npm"