name: Build/release

# Run this script when pushing to a tag that starts with 'v'
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            platform: darwin
          - os: ubuntu-latest
            platform: linux

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Build Electron app
        uses: netruk44/electron-forge-distributable-action@publish-action
        with:
          target-maker: "@electron-forge/maker-zip"
          target-platform: ${{ matrix.platform }}
          node-installer: "npm"
          working-directory: "./borg-explorer"
          github-token: ${{ secrets.github_token }}